name: prompt-ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint & Format Check
        run: |
          ruff check .
          black --check .

      - name: Validate prompt schema
        run: python scripts/validate_schema.py

      - name: Run tests
        run: pytest -q --disable-warnings

      - name: Offline prompt evaluation
        run: python scripts/eval_prompts.py

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: eval-report
          path: eval_report.md
